name: Automatisation des tests DevSecOps
on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug (où est le requirements.txt ?)
        run: |
          pwd
          ls -la
          echo "---- contenu breakableflask/ ----"
          ls -la breakableflask || true

      - name: Scan des dépendances (Trivy FS sur le bon dossier)
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/project \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest fs --scanners vuln,secret /project/breakableflask \
            --exit-code 1 --severity HIGH,CRITICAL || true


  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build image
        run: |
          docker build -t imgvulne:1.1 .

      - name: Scan de l'image (Trivy Image)
        run: |
          set -euo pipefail
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.cache/trivy":/root/.cache/ \
            aquasec/trivy:latest image --format json --severity HIGH,CRITICAL imgvulne:1.1 \
          | jq -r '
              ["TARGET","PACKAGE","INSTALLED","VULN","SEVERITY"],
              (.Results[]? as $r | $r.Vulnerabilities[]? | [$r.Target, .PkgName, .InstalledVersion, .VulnerabilityID, .Severity])
              | @tsv' \
          | column -t -s $'\t'

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: echo "Rien à faire ici. Votre application est prête à être déployée"
